version: '3.8'

services:

  app:
    build:
      context: .
    image: laravel-api-app
    container_name: laravel-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
      - vendor:/var/www/vendor
    expose:
      - "9000"
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: laravel-api-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api:/var/www:ro
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: top5_tiao_carreiro
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
  vendor:
